debug: false

management:
  health.diskspace.enabled: false
  endpoints.web.exposure.include: "*"

logging.level:
  root: info
  me.h2s.jedis.multi.online.config: debug

spring:
  profiles:
    active: local
  redis-global:
    host: localhost
    port: 6379
  redis-local:
    host: localhost
    port: 6378
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect


